# Generated by Django 3.1.4 on 2020-12-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=200)),
                ('hire_date', models.DateTimeField()),
                ('timesheet_date', models.DateTimeField()),
                ('day_worked_hours', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
